spring:
  application:
    name: order-service
    outbox:
      listener:
        topics: ${OUTBOX_TOPICS}
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  sql:
    init:
      mode: never
  kafka:
    bootstrap-servers: ${KAFKA_URI:localhost:9092}
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: com.ecommerce.outbox
          value:
            default.type: com.ecommerce.outbox.events.OutboxEvent

management:
  endpoint:
    health:
      access: read_only
      show-details: always # ok in the private network, must override to 'when_authorized' in the public
      show-components: always
      cache:
        time-to-live: 5s
    configprops: # secured info
      access: read_only
  endpoints:
    access:
      default: read_only
    web:
      exposure:
        # logfile,loggers,env,configprops,threaddump,flyway - useful, but does not safe
        include: info,health,metrics,prometheus,logfile,loggers,env,configprops,threaddump,flyway
      cors:
        # ok in the private network, must override to allow from the specified front end
        allowed-origins: "*"
        allowed-methods: GET
    jmx:
      exposure:
        exclude=*:
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    mail:
      enabled: false
  metrics:
    enable:
      logback: true
      jvm: true
      process:
        files: true
    distribution:
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
      percentiles-histogram:
        all: true
